apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
spec:
  type: NodePort
  selector:
    app: devops-api  # Doit correspondre au label du pod
  ports:
    - protocol: TCP
      port: 80         # Port interne du cluster
      targetPort: 8080 # Port de ton application Spring Boot
      nodePort: 30000  # Port optionnel pour acc√®s direct